title: Econ on metrics
description: >
  **Econ-on-metrics** est un projet de blogging scientifique général discutant de statistiques
  appliquées à différent domaines comme la **Finance**, **l'Environnement** et l'**Economie** en générale.
  Avec une attention particulière sur l'utilisation du logiciel **R**. Je suis Ludovic Vigneron, Maître de Conférence
  à l'Université de Valenciennes membre du laboratoire IDP.
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username:
twitter_username: "#"
linkedin_username: "#"
instagram_username:
pinterest_username:
flickr_username:
github_username:  "#"
feed_icon: rss
email: ludovic.vigneron@univ-valenciennes.fr
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
